observation_keep_time: 0
expected_update_rate: 10
min_obstacle_height: 0.0
max_obstacle_height: 2.0
obstacle_range: 5
raytrace_range: 5
transform_tolerance: 0.3
topic_string: "base_scan"
sensor_frame: "base_laser_link"
inf_is_valid: false
clearing: true
footprint_clearing_enabled: true
marking: true
is_debug: true


map_topic: "map"
enemy_inflation: 0.2
max_occ_dist: 5.0


